### ISSUE TITLE
helm-org-in-buffer-headings only returns 100 entries

### ISSUE THREAD

**Issue by vv111y** [emacs-helm/helm-org#11]
Not sure what else I should report. I looked at customisations and variables for both helm and helm-org and could find nothing on some set limit. How do I set it so that all headings are returned? Thanks

**Comment by thierryvolpiatto** [comment]
vv111y <notifications@github.com> writes:

> Not sure what else I should report. I looked at customisations and
> variables for both helm and helm-org and could find nothing on some
> set limit. How do I set it so that all headings are returned?

Increase `helm-candidate-number-limit`.

However, it is not because you don't see all the candidates in your
display that they are not reachable, if you narrow down the list of
candidates you will match your candidate(s), so no need to increase this
list too much (I use 500).

Also keep in mind this is a global var that will affect all your helm
sources.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by vv111y** [comment]
Couldn't find the right var anywhere, thanks!
